import { MigrationInterface, QueryRunner } from "typeorm";

export class mg1655717392090 implements MigrationInterface {
    name = 'mg1655717392090'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`address_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`type\` int NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`parentId\` int NULL, INDEX \`IDX_04e1759cfac6874f76e2a11721\` (\`name\`), INDEX \`IDX_39d5f5d0d49f93a617b13b61fe\` (\`type\`), INDEX \`IDX_bb6ca3fd9ceb44a47859a43869\` (\`name\`, \`type\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`skill_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_f9600b0068f542043fc61430c8\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`company_info_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`addressStreet\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`companyName\` varchar(255) NOT NULL, \`dayEstablish\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`addressProvinceId\` int NULL, \`addressDistrictId\` int NULL, \`addressVillageId\` int NULL, UNIQUE INDEX \`REL_bbd7576066b053fc16f76617e0\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_info_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`addressStreet\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`fullName\` varchar(255) NOT NULL, \`birthday\` datetime NOT NULL, \`interest\` varchar(65000) NOT NULL, \`objective\` varchar(65000) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`addressProvinceId\` int NULL, \`addressDistrictId\` int NULL, \`addressVillageId\` int NULL, \`jobLevelId\` int NULL, UNIQUE INDEX \`REL_9c391e2018f807b6843cdee35c\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`job_level_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_bd3ae16a1281da016b39e86fef\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`work_from_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_b9ff15431d6b348f7b02f430d4\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`position_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_5aa970b42f0a6ce72351658bd2\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_position_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`level\` int NOT NULL DEFAULT '1', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`positionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_work_experience_position_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`cvWorkExperienceId\` int NULL, \`userPositionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_work_experience_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`companyName\` varchar(255) NOT NULL, \`content\` varchar(65000) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`companyInfoId\` int NULL, \`jobLevelId\` int NULL, \`workFromId\` int NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_work_experience_skill_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`cvWorkExperienceId\` int NULL, \`userSkillId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_skill_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`level\` int NOT NULL DEFAULT '1', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`skillId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ranked_academic_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`school_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_c153fa4cf5a2c086bc453a034b\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_education_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`mark\` int NOT NULL, \`content\` varchar(65000) NOT NULL, \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`rankedAcademicId\` int NULL, \`schoolId\` int NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_activities_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`role\` varchar(255) NOT NULL, \`content\` varchar(65000) NOT NULL, \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_honors_awards_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`content\` varchar(65000) NOT NULL, \`startDate\` datetime NOT NULL, \`endDate\` datetime NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_certificate_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`date\` datetime NOT NULL, \`content\` varchar(65000) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userCertificateId\` int NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`role\` varchar(255) NOT NULL DEFAULT 'begin', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_415c35b9b3b6fe45a3b065030f\` (\`email\`), INDEX \`IDX_158f20832b16ead19dcd50c743\` (\`role\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_certificate_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`level\` int NOT NULL DEFAULT '1', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`certificateId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`certificate_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_ee4950f4e4c1764b45288bd631\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` ADD CONSTRAINT \`FK_d96e5f9914d0f80c787b8da289b\` FOREIGN KEY (\`parentId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_bbd7576066b053fc16f76617e00\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_5e416a6fdc03f66de9b51d6e96a\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_a30325f01e55247deb78498649a\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_e23e7775e939d1ae14b4e7ee473\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_9c391e2018f807b6843cdee35ca\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_165d4ff9dcabc15def46ffa8c20\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_0d66f3e9f22d5e62be548a6f02b\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_1b8bcad73a6becddb565dc4efd7\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_e7b0e7181fd855f9f1e812e592b\` FOREIGN KEY (\`jobLevelId\`) REFERENCES \`job_level_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_4bb7b007ab6347dad742d533715\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_8f6fff6b2239738702560ddb52b\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` ADD CONSTRAINT \`FK_d2bc7c7b359750c32dfed9bdc76\` FOREIGN KEY (\`cvWorkExperienceId\`) REFERENCES \`cv_work_experience_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` ADD CONSTRAINT \`FK_3a5ce6c844f73b331cbf0443131\` FOREIGN KEY (\`userPositionId\`) REFERENCES \`user_position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_6502de04b0fdc508b161c56ed9e\` FOREIGN KEY (\`companyInfoId\`) REFERENCES \`company_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_1b3900fd8753c2ca7f5daaf0afd\` FOREIGN KEY (\`jobLevelId\`) REFERENCES \`job_level_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_6b0550abd4604060249ef3aca5b\` FOREIGN KEY (\`workFromId\`) REFERENCES \`work_from_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_e79ee65cc62f38c795d889691d6\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` ADD CONSTRAINT \`FK_934c6ac69085740dd8f746d78e8\` FOREIGN KEY (\`cvWorkExperienceId\`) REFERENCES \`cv_work_experience_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` ADD CONSTRAINT \`FK_e035290932d0b086aa555b579d7\` FOREIGN KEY (\`userSkillId\`) REFERENCES \`user_skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_401509d24b0d71b01a0a0b98756\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_10b2a273ef381e46ae6fc67aa46\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_3152c2efd3647b7aa68f0743690\` FOREIGN KEY (\`rankedAcademicId\`) REFERENCES \`ranked_academic_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_3a4584dd964dbef7194e4b3734c\` FOREIGN KEY (\`schoolId\`) REFERENCES \`school_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_52ab40f5accd7c3d6bc100389b7\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` ADD CONSTRAINT \`FK_87a1829647c584d7ac7a0e70296\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` ADD CONSTRAINT \`FK_7652c87043fce32940a34c20153\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` ADD CONSTRAINT \`FK_d2a6db9c4d2b6c0484eabd96d7d\` FOREIGN KEY (\`userCertificateId\`) REFERENCES \`user_certificate_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` ADD CONSTRAINT \`FK_7ace3a698f0341fa84d6558e828\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` ADD CONSTRAINT \`FK_789640cfc0373a2d3442c1c5bbf\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` ADD CONSTRAINT \`FK_cbcff6bccb35fe0a22d56c88b5d\` FOREIGN KEY (\`certificateId\`) REFERENCES \`certificate_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` DROP FOREIGN KEY \`FK_cbcff6bccb35fe0a22d56c88b5d\``);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` DROP FOREIGN KEY \`FK_789640cfc0373a2d3442c1c5bbf\``);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` DROP FOREIGN KEY \`FK_7ace3a698f0341fa84d6558e828\``);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` DROP FOREIGN KEY \`FK_d2a6db9c4d2b6c0484eabd96d7d\``);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` DROP FOREIGN KEY \`FK_7652c87043fce32940a34c20153\``);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` DROP FOREIGN KEY \`FK_87a1829647c584d7ac7a0e70296\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_52ab40f5accd7c3d6bc100389b7\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_3a4584dd964dbef7194e4b3734c\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_3152c2efd3647b7aa68f0743690\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_10b2a273ef381e46ae6fc67aa46\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_401509d24b0d71b01a0a0b98756\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` DROP FOREIGN KEY \`FK_e035290932d0b086aa555b579d7\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` DROP FOREIGN KEY \`FK_934c6ac69085740dd8f746d78e8\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_e79ee65cc62f38c795d889691d6\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_6b0550abd4604060249ef3aca5b\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_1b3900fd8753c2ca7f5daaf0afd\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_6502de04b0fdc508b161c56ed9e\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` DROP FOREIGN KEY \`FK_3a5ce6c844f73b331cbf0443131\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` DROP FOREIGN KEY \`FK_d2bc7c7b359750c32dfed9bdc76\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_8f6fff6b2239738702560ddb52b\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_4bb7b007ab6347dad742d533715\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_e7b0e7181fd855f9f1e812e592b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_1b8bcad73a6becddb565dc4efd7\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_0d66f3e9f22d5e62be548a6f02b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_165d4ff9dcabc15def46ffa8c20\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_9c391e2018f807b6843cdee35ca\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_e23e7775e939d1ae14b4e7ee473\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_a30325f01e55247deb78498649a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_5e416a6fdc03f66de9b51d6e96a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_bbd7576066b053fc16f76617e00\``);
        await queryRunner.query(`ALTER TABLE \`address_entity\` DROP FOREIGN KEY \`FK_d96e5f9914d0f80c787b8da289b\``);
        await queryRunner.query(`DROP INDEX \`IDX_ee4950f4e4c1764b45288bd631\` ON \`certificate_entity\``);
        await queryRunner.query(`DROP TABLE \`certificate_entity\``);
        await queryRunner.query(`DROP TABLE \`user_certificate_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_158f20832b16ead19dcd50c743\` ON \`user_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_415c35b9b3b6fe45a3b065030f\` ON \`user_entity\``);
        await queryRunner.query(`DROP TABLE \`user_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_certificate_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_honors_awards_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_activities_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_education_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_c153fa4cf5a2c086bc453a034b\` ON \`school_entity\``);
        await queryRunner.query(`DROP TABLE \`school_entity\``);
        await queryRunner.query(`DROP TABLE \`ranked_academic_entity\``);
        await queryRunner.query(`DROP TABLE \`user_skill_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_work_experience_skill_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_work_experience_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_work_experience_position_entity\``);
        await queryRunner.query(`DROP TABLE \`user_position_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_5aa970b42f0a6ce72351658bd2\` ON \`position_entity\``);
        await queryRunner.query(`DROP TABLE \`position_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_b9ff15431d6b348f7b02f430d4\` ON \`work_from_entity\``);
        await queryRunner.query(`DROP TABLE \`work_from_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_bd3ae16a1281da016b39e86fef\` ON \`job_level_entity\``);
        await queryRunner.query(`DROP TABLE \`job_level_entity\``);
        await queryRunner.query(`DROP INDEX \`REL_9c391e2018f807b6843cdee35c\` ON \`user_info_entity\``);
        await queryRunner.query(`DROP TABLE \`user_info_entity\``);
        await queryRunner.query(`DROP INDEX \`REL_bbd7576066b053fc16f76617e0\` ON \`company_info_entity\``);
        await queryRunner.query(`DROP TABLE \`company_info_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_f9600b0068f542043fc61430c8\` ON \`skill_entity\``);
        await queryRunner.query(`DROP TABLE \`skill_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_bb6ca3fd9ceb44a47859a43869\` ON \`address_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_39d5f5d0d49f93a617b13b61fe\` ON \`address_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_04e1759cfac6874f76e2a11721\` ON \`address_entity\``);
        await queryRunner.query(`DROP TABLE \`address_entity\``);
    }

}
