import { MigrationInterface, QueryRunner } from "typeorm";

export class mg1655676580200 implements MigrationInterface {
    name = 'mg1655676580200'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_entity\` DROP FOREIGN KEY \`FK_0934e734a3f97d37788198f296c\``);
        await queryRunner.query(`ALTER TABLE \`user_entity\` DROP FOREIGN KEY \`FK_5e96f265469267c6c27191b6877\``);
        await queryRunner.query(`DROP INDEX \`REL_0934e734a3f97d37788198f296\` ON \`user_entity\``);
        await queryRunner.query(`DROP INDEX \`REL_5e96f265469267c6c27191b687\` ON \`user_entity\``);
        await queryRunner.query(`CREATE TABLE \`cv_sec_control_data_skill_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`level\` int NOT NULL DEFAULT '1', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`cvSecControlDataId\` int NULL, \`skillId\` int NULL, \`userId\` int NULL, INDEX \`IDX_306145628765907330d1b91ae8\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` DROP COLUMN \`userInfoId\``);
        await queryRunner.query(`ALTER TABLE \`user_entity\` DROP COLUMN \`companyInfoId\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD UNIQUE INDEX \`IDX_9c391e2018f807b6843cdee35c\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` ADD \`text\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD UNIQUE INDEX \`IDX_bbd7576066b053fc16f76617e0\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_401509d24b0d71b01a0a0b98756\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_10b2a273ef381e46ae6fc67aa46\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` DROP FOREIGN KEY \`FK_d96e5f9914d0f80c787b8da289b\``);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`parentId\` \`parentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`job_level_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_165d4ff9dcabc15def46ffa8c20\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_0d66f3e9f22d5e62be548a6f02b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_1b8bcad73a6becddb565dc4efd7\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_e7b0e7181fd855f9f1e812e592b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`jobLevelId\` \`jobLevelId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_section_control_type_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` DROP FOREIGN KEY \`FK_3e05bb5c8b559bcf99086887e67\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` DROP FOREIGN KEY \`FK_b43fe610aeff5d2c50e36b22724\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` CHANGE \`cvSecBuilderId\` \`cvSecBuilderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_row_entity\` DROP FOREIGN KEY \`FK_d16f79b6b89b5bdf57e99ee8701\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_row_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_row_entity\` CHANGE \`cvSecDataId\` \`cvSecDataId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` DROP FOREIGN KEY \`FK_c9f534b44b76e35620cd7fe7165\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` DROP FOREIGN KEY \`FK_e06fd1a4dc343d7e33b578f0404\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` CHANGE \`cvSecDataRowId\` \`cvSecDataRowId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` CHANGE \`cvSecBuilderSectionControlTypeId\` \`cvSecBuilderSectionControlTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_control_select_type_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` DROP FOREIGN KEY \`FK_dddd91861299432578ea49ccb59\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` DROP FOREIGN KEY \`FK_29b90730a1a208c7b54a1eee9b0\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` DROP FOREIGN KEY \`FK_4317c257e253e4012b8cdda3e47\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` CHANGE \`cvControlSelectTypeId\` \`cvControlSelectTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` CHANGE \`cvSecBuilderId\` \`cvSecBuilderId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` CHANGE \`cvSectionControlTypeId\` \`cvSectionControlTypeId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` DROP FOREIGN KEY \`FK_7c99c304cf66aeed6e382e352cc\``);
        await queryRunner.query(`DROP INDEX \`userId_name_unique\` ON \`cv_sec_builder_entity\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_5e416a6fdc03f66de9b51d6e96a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_a30325f01e55247deb78498649a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_e23e7775e939d1ae14b4e7ee473\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_4bb7b007ab6347dad742d533715\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_8f6fff6b2239738702560ddb52b\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_from_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_9c391e2018f807b6843cdee35c\` ON \`user_info_entity\` (\`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`userId_name_unique\` ON \`cv_sec_builder_entity\` (\`name\`, \`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_bbd7576066b053fc16f76617e0\` ON \`company_info_entity\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_401509d24b0d71b01a0a0b98756\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_10b2a273ef381e46ae6fc67aa46\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` ADD CONSTRAINT \`FK_d96e5f9914d0f80c787b8da289b\` FOREIGN KEY (\`parentId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_9c391e2018f807b6843cdee35ca\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_165d4ff9dcabc15def46ffa8c20\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_0d66f3e9f22d5e62be548a6f02b\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_1b8bcad73a6becddb565dc4efd7\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_e7b0e7181fd855f9f1e812e592b\` FOREIGN KEY (\`jobLevelId\`) REFERENCES \`job_level_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` ADD CONSTRAINT \`FK_3e05bb5c8b559bcf99086887e67\` FOREIGN KEY (\`cvSecBuilderId\`) REFERENCES \`cv_sec_builder_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` ADD CONSTRAINT \`FK_b43fe610aeff5d2c50e36b22724\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_row_entity\` ADD CONSTRAINT \`FK_d16f79b6b89b5bdf57e99ee8701\` FOREIGN KEY (\`cvSecDataId\`) REFERENCES \`cv_sec_data_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_skill_entity\` ADD CONSTRAINT \`FK_86d87fbcd5cf6391e56ebebd880\` FOREIGN KEY (\`cvSecControlDataId\`) REFERENCES \`cv_sec_control_data_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_skill_entity\` ADD CONSTRAINT \`FK_d31c5b86f25b51b4f2e7c17e7ab\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_skill_entity\` ADD CONSTRAINT \`FK_eddcdcd1f30d7693ac5e00b86fe\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` ADD CONSTRAINT \`FK_c9f534b44b76e35620cd7fe7165\` FOREIGN KEY (\`cvSecDataRowId\`) REFERENCES \`cv_sec_data_row_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` ADD CONSTRAINT \`FK_e06fd1a4dc343d7e33b578f0404\` FOREIGN KEY (\`cvSecBuilderSectionControlTypeId\`) REFERENCES \`cv_sec_builder_section_control_type_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` ADD CONSTRAINT \`FK_dddd91861299432578ea49ccb59\` FOREIGN KEY (\`cvControlSelectTypeId\`) REFERENCES \`cv_control_select_type_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` ADD CONSTRAINT \`FK_29b90730a1a208c7b54a1eee9b0\` FOREIGN KEY (\`cvSecBuilderId\`) REFERENCES \`cv_sec_builder_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` ADD CONSTRAINT \`FK_4317c257e253e4012b8cdda3e47\` FOREIGN KEY (\`cvSectionControlTypeId\`) REFERENCES \`cv_section_control_type_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` ADD CONSTRAINT \`FK_7c99c304cf66aeed6e382e352cc\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_bbd7576066b053fc16f76617e00\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_5e416a6fdc03f66de9b51d6e96a\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_a30325f01e55247deb78498649a\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_e23e7775e939d1ae14b4e7ee473\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_4bb7b007ab6347dad742d533715\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_8f6fff6b2239738702560ddb52b\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_8f6fff6b2239738702560ddb52b\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_4bb7b007ab6347dad742d533715\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_e23e7775e939d1ae14b4e7ee473\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_a30325f01e55247deb78498649a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_5e416a6fdc03f66de9b51d6e96a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_bbd7576066b053fc16f76617e00\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` DROP FOREIGN KEY \`FK_7c99c304cf66aeed6e382e352cc\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` DROP FOREIGN KEY \`FK_4317c257e253e4012b8cdda3e47\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` DROP FOREIGN KEY \`FK_29b90730a1a208c7b54a1eee9b0\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` DROP FOREIGN KEY \`FK_dddd91861299432578ea49ccb59\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` DROP FOREIGN KEY \`FK_e06fd1a4dc343d7e33b578f0404\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` DROP FOREIGN KEY \`FK_c9f534b44b76e35620cd7fe7165\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_skill_entity\` DROP FOREIGN KEY \`FK_eddcdcd1f30d7693ac5e00b86fe\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_skill_entity\` DROP FOREIGN KEY \`FK_d31c5b86f25b51b4f2e7c17e7ab\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_skill_entity\` DROP FOREIGN KEY \`FK_86d87fbcd5cf6391e56ebebd880\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_row_entity\` DROP FOREIGN KEY \`FK_d16f79b6b89b5bdf57e99ee8701\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` DROP FOREIGN KEY \`FK_b43fe610aeff5d2c50e36b22724\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` DROP FOREIGN KEY \`FK_3e05bb5c8b559bcf99086887e67\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_e7b0e7181fd855f9f1e812e592b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_1b8bcad73a6becddb565dc4efd7\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_0d66f3e9f22d5e62be548a6f02b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_165d4ff9dcabc15def46ffa8c20\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_9c391e2018f807b6843cdee35ca\``);
        await queryRunner.query(`ALTER TABLE \`address_entity\` DROP FOREIGN KEY \`FK_d96e5f9914d0f80c787b8da289b\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_10b2a273ef381e46ae6fc67aa46\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_401509d24b0d71b01a0a0b98756\``);
        await queryRunner.query(`DROP INDEX \`REL_bbd7576066b053fc16f76617e0\` ON \`company_info_entity\``);
        await queryRunner.query(`DROP INDEX \`userId_name_unique\` ON \`cv_sec_builder_entity\``);
        await queryRunner.query(`DROP INDEX \`REL_9c391e2018f807b6843cdee35c\` ON \`user_info_entity\``);
        await queryRunner.query(`ALTER TABLE \`work_from_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_8f6fff6b2239738702560ddb52b\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_4bb7b007ab6347dad742d533715\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_e23e7775e939d1ae14b4e7ee473\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_a30325f01e55247deb78498649a\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_5e416a6fdc03f66de9b51d6e96a\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`userId_name_unique\` ON \`cv_sec_builder_entity\` (\`name\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` ADD CONSTRAINT \`FK_7c99c304cf66aeed6e382e352cc\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` CHANGE \`cvSectionControlTypeId\` \`cvSectionControlTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` CHANGE \`cvSecBuilderId\` \`cvSecBuilderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` CHANGE \`cvControlSelectTypeId\` \`cvControlSelectTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` ADD CONSTRAINT \`FK_4317c257e253e4012b8cdda3e47\` FOREIGN KEY (\`cvSectionControlTypeId\`) REFERENCES \`cv_section_control_type_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` ADD CONSTRAINT \`FK_29b90730a1a208c7b54a1eee9b0\` FOREIGN KEY (\`cvSecBuilderId\`) REFERENCES \`cv_sec_builder_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` ADD CONSTRAINT \`FK_dddd91861299432578ea49ccb59\` FOREIGN KEY (\`cvControlSelectTypeId\`) REFERENCES \`cv_control_select_type_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_control_select_type_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` CHANGE \`cvSecBuilderSectionControlTypeId\` \`cvSecBuilderSectionControlTypeId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` CHANGE \`cvSecDataRowId\` \`cvSecDataRowId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` ADD CONSTRAINT \`FK_e06fd1a4dc343d7e33b578f0404\` FOREIGN KEY (\`cvSecBuilderSectionControlTypeId\`) REFERENCES \`cv_sec_builder_section_control_type_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` ADD CONSTRAINT \`FK_c9f534b44b76e35620cd7fe7165\` FOREIGN KEY (\`cvSecDataRowId\`) REFERENCES \`cv_sec_data_row_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_row_entity\` CHANGE \`cvSecDataId\` \`cvSecDataId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_row_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_row_entity\` ADD CONSTRAINT \`FK_d16f79b6b89b5bdf57e99ee8701\` FOREIGN KEY (\`cvSecDataId\`) REFERENCES \`cv_sec_data_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` CHANGE \`cvSecBuilderId\` \`cvSecBuilderId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` ADD CONSTRAINT \`FK_b43fe610aeff5d2c50e36b22724\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_data_entity\` ADD CONSTRAINT \`FK_3e05bb5c8b559bcf99086887e67\` FOREIGN KEY (\`cvSecBuilderId\`) REFERENCES \`cv_sec_builder_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_section_control_type_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`jobLevelId\` \`jobLevelId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_e7b0e7181fd855f9f1e812e592b\` FOREIGN KEY (\`jobLevelId\`) REFERENCES \`job_level_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_1b8bcad73a6becddb565dc4efd7\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_0d66f3e9f22d5e62be548a6f02b\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_165d4ff9dcabc15def46ffa8c20\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`job_level_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`parentId\` \`parentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` ADD CONSTRAINT \`FK_d96e5f9914d0f80c787b8da289b\` FOREIGN KEY (\`parentId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_10b2a273ef381e46ae6fc67aa46\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_401509d24b0d71b01a0a0b98756\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP INDEX \`IDX_bbd7576066b053fc16f76617e0\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_control_data_entity\` DROP COLUMN \`text\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP INDEX \`IDX_9c391e2018f807b6843cdee35c\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`user_entity\` ADD \`companyInfoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` ADD \`userInfoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`DROP INDEX \`IDX_306145628765907330d1b91ae8\` ON \`cv_sec_control_data_skill_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_sec_control_data_skill_entity\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_5e96f265469267c6c27191b687\` ON \`user_entity\` (\`companyInfoId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_0934e734a3f97d37788198f296\` ON \`user_entity\` (\`userInfoId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` ADD CONSTRAINT \`FK_5e96f265469267c6c27191b6877\` FOREIGN KEY (\`companyInfoId\`) REFERENCES \`company_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` ADD CONSTRAINT \`FK_0934e734a3f97d37788198f296c\` FOREIGN KEY (\`userInfoId\`) REFERENCES \`user_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
