import { MigrationInterface, QueryRunner } from "typeorm";

export class mg1655932060785 implements MigrationInterface {
    name = 'mg1655932060785'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` DROP COLUMN \`date\``);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` ADD \`year\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` DROP FOREIGN KEY \`FK_d96e5f9914d0f80c787b8da289b\``);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`parentId\` \`parentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_9c391e2018f807b6843cdee35ca\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_165d4ff9dcabc15def46ffa8c20\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_0d66f3e9f22d5e62be548a6f02b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_1b8bcad73a6becddb565dc4efd7\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_e7b0e7181fd855f9f1e812e592b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`interest\` \`interest\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`objective\` \`objective\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`jobLevelId\` \`jobLevelId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`job_level_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`work_from_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_4bb7b007ab6347dad742d533715\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_8f6fff6b2239738702560ddb52b\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8bac637b3db062b19fc103cf2\` ON \`user_position_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` DROP FOREIGN KEY \`FK_61b6e6c0ebe5a443ad738f394d5\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` DROP FOREIGN KEY \`FK_cee737ea7a02788a001cdd9ebab\``);
        await queryRunner.query(`DROP INDEX \`IDX_d8d247814af7dbb26a8ae81f54\` ON \`user_tagged_position_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` DROP FOREIGN KEY \`FK_d2bc7c7b359750c32dfed9bdc76\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` DROP FOREIGN KEY \`FK_88e7580f6462c6b098083daeba1\``);
        await queryRunner.query(`DROP INDEX \`IDX_edea0cf6b6e524794e2324de90\` ON \`cv_work_experience_position_entity\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` CHANGE \`cvWorkExperienceId\` \`cvWorkExperienceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` DROP FOREIGN KEY \`FK_5cb06862a9b92d9f8639209d162\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` DROP FOREIGN KEY \`FK_d0f523287bb6a13d53905962391\``);
        await queryRunner.query(`DROP INDEX \`IDX_fdb82033eaa6d2f4cf7a44bbd3\` ON \`user_tagged_company_tag_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` CHANGE \`companyTagId\` \`companyTagId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_bbd7576066b053fc16f76617e00\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_5e416a6fdc03f66de9b51d6e96a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_a30325f01e55247deb78498649a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_e23e7775e939d1ae14b4e7ee473\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_tag_entity\` DROP FOREIGN KEY \`FK_0abbd4350f976aabf730c5ba4c7\``);
        await queryRunner.query(`ALTER TABLE \`company_tag_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_tag_entity\` CHANGE \`companyInfoId\` \`companyInfoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_5c10cf491690ed4d710718060b3\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_1b3900fd8753c2ca7f5daaf0afd\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_6b0550abd4604060249ef3aca5b\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_e79ee65cc62f38c795d889691d6\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`endDate\` \`endDate\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`content\` \`content\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`companyTagId\` \`companyTagId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`jobLevelId\` \`jobLevelId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`workFromId\` \`workFromId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` DROP FOREIGN KEY \`FK_934c6ac69085740dd8f746d78e8\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` DROP FOREIGN KEY \`FK_7847c58187237b0e4b346cd49ef\``);
        await queryRunner.query(`DROP INDEX \`IDX_8c99e8dfb3daee272748878669\` ON \`cv_work_experience_skill_entity\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` CHANGE \`cvWorkExperienceId\` \`cvWorkExperienceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` DROP FOREIGN KEY \`FK_8b9dfbac4c8959963a7c966d9b8\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` DROP FOREIGN KEY \`FK_24eca45ff584c922bdc0feef184\``);
        await queryRunner.query(`DROP INDEX \`IDX_3f52e8df570dd7586c12a7dadd\` ON \`user_tagged_skill_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_401509d24b0d71b01a0a0b98756\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_10b2a273ef381e46ae6fc67aa46\``);
        await queryRunner.query(`DROP INDEX \`IDX_d569718f45522c277173602332\` ON \`user_skill_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`ranked_academic_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` DROP FOREIGN KEY \`FK_1e728f6d21307865790753ee148\``);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` DROP FOREIGN KEY \`FK_1925ddf100616fa4d0b3e62574b\``);
        await queryRunner.query(`DROP INDEX \`IDX_6b92f1f20f2469c59d3780fc06\` ON \`user_school_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` CHANGE \`schoolId\` \`schoolId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` DROP FOREIGN KEY \`FK_fe228a77fedbe9033278b705a18\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` DROP FOREIGN KEY \`FK_ab153f36e61d7c0d0ccc945a0ea\``);
        await queryRunner.query(`DROP INDEX \`IDX_9aac5475ecef981ded65e4f795\` ON \`user_tagged_school_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` CHANGE \`schoolId\` \`schoolId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`school_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_3152c2efd3647b7aa68f0743690\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_3a4584dd964dbef7194e4b3734c\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_52ab40f5accd7c3d6bc100389b7\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`content\` \`content\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`rankedAcademicId\` \`rankedAcademicId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`schoolId\` \`schoolId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` DROP FOREIGN KEY \`FK_7652c87043fce32940a34c20153\``);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` DROP FOREIGN KEY \`FK_02fcbe5517ce42bbf470ab1d7ae\``);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` DROP FOREIGN KEY \`FK_7ace3a698f0341fa84d6558e828\``);
        await queryRunner.query(`DROP INDEX \`IDX_17047910dd948275a7fbaec3ff\` ON \`cv_certificate_entity\``);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` CHANGE \`content\` \`content\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` CHANGE \`certificateId\` \`certificateId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` DROP FOREIGN KEY \`FK_48c0503ac7bbf1d96d26fb9c356\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` DROP FOREIGN KEY \`FK_c312553cc0e1a4328d69eb4d449\``);
        await queryRunner.query(`DROP INDEX \`IDX_137366505dda765a2502e46f2f\` ON \`user_tagged_certificate_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` CHANGE \`certificateId\` \`certificateId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`certificate_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` DROP FOREIGN KEY \`FK_789640cfc0373a2d3442c1c5bbf\``);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` DROP FOREIGN KEY \`FK_cbcff6bccb35fe0a22d56c88b5d\``);
        await queryRunner.query(`DROP INDEX \`IDX_88a1485872bf594d91855aaf99\` ON \`user_certificate_entity\``);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` CHANGE \`certificateId\` \`certificateId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` DROP FOREIGN KEY \`FK_87a1829647c584d7ac7a0e70296\``);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_c8bac637b3db062b19fc103cf2\` ON \`user_position_entity\` (\`positionId\`, \`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d8d247814af7dbb26a8ae81f54\` ON \`user_tagged_position_entity\` (\`positionId\`, \`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_edea0cf6b6e524794e2324de90\` ON \`cv_work_experience_position_entity\` (\`cvWorkExperienceId\`, \`positionId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_fdb82033eaa6d2f4cf7a44bbd3\` ON \`user_tagged_company_tag_entity\` (\`companyTagId\`, \`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_8c99e8dfb3daee272748878669\` ON \`cv_work_experience_skill_entity\` (\`cvWorkExperienceId\`, \`skillId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_3f52e8df570dd7586c12a7dadd\` ON \`user_tagged_skill_entity\` (\`skillId\`, \`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d569718f45522c277173602332\` ON \`user_skill_entity\` (\`skillId\`, \`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_6b92f1f20f2469c59d3780fc06\` ON \`user_school_entity\` (\`schoolId\`, \`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9aac5475ecef981ded65e4f795\` ON \`user_tagged_school_entity\` (\`schoolId\`, \`userId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_17047910dd948275a7fbaec3ff\` ON \`cv_certificate_entity\` (\`userId\`, \`certificateId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_137366505dda765a2502e46f2f\` ON \`user_tagged_certificate_entity\` (\`userId\`, \`certificateId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_88a1485872bf594d91855aaf99\` ON \`user_certificate_entity\` (\`userId\`, \`certificateId\`)`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` ADD CONSTRAINT \`FK_d96e5f9914d0f80c787b8da289b\` FOREIGN KEY (\`parentId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_9c391e2018f807b6843cdee35ca\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_165d4ff9dcabc15def46ffa8c20\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_0d66f3e9f22d5e62be548a6f02b\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_1b8bcad73a6becddb565dc4efd7\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_e7b0e7181fd855f9f1e812e592b\` FOREIGN KEY (\`jobLevelId\`) REFERENCES \`job_level_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_4bb7b007ab6347dad742d533715\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_8f6fff6b2239738702560ddb52b\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` ADD CONSTRAINT \`FK_61b6e6c0ebe5a443ad738f394d5\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` ADD CONSTRAINT \`FK_cee737ea7a02788a001cdd9ebab\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` ADD CONSTRAINT \`FK_d2bc7c7b359750c32dfed9bdc76\` FOREIGN KEY (\`cvWorkExperienceId\`) REFERENCES \`cv_work_experience_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` ADD CONSTRAINT \`FK_88e7580f6462c6b098083daeba1\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` ADD CONSTRAINT \`FK_5cb06862a9b92d9f8639209d162\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` ADD CONSTRAINT \`FK_d0f523287bb6a13d53905962391\` FOREIGN KEY (\`companyTagId\`) REFERENCES \`company_tag_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_bbd7576066b053fc16f76617e00\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_5e416a6fdc03f66de9b51d6e96a\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_a30325f01e55247deb78498649a\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_e23e7775e939d1ae14b4e7ee473\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_tag_entity\` ADD CONSTRAINT \`FK_0abbd4350f976aabf730c5ba4c7\` FOREIGN KEY (\`companyInfoId\`) REFERENCES \`company_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_5c10cf491690ed4d710718060b3\` FOREIGN KEY (\`companyTagId\`) REFERENCES \`company_tag_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_1b3900fd8753c2ca7f5daaf0afd\` FOREIGN KEY (\`jobLevelId\`) REFERENCES \`job_level_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_6b0550abd4604060249ef3aca5b\` FOREIGN KEY (\`workFromId\`) REFERENCES \`work_from_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_e79ee65cc62f38c795d889691d6\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` ADD CONSTRAINT \`FK_934c6ac69085740dd8f746d78e8\` FOREIGN KEY (\`cvWorkExperienceId\`) REFERENCES \`cv_work_experience_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` ADD CONSTRAINT \`FK_7847c58187237b0e4b346cd49ef\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` ADD CONSTRAINT \`FK_8b9dfbac4c8959963a7c966d9b8\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` ADD CONSTRAINT \`FK_24eca45ff584c922bdc0feef184\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_401509d24b0d71b01a0a0b98756\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_10b2a273ef381e46ae6fc67aa46\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` ADD CONSTRAINT \`FK_1e728f6d21307865790753ee148\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` ADD CONSTRAINT \`FK_1925ddf100616fa4d0b3e62574b\` FOREIGN KEY (\`schoolId\`) REFERENCES \`school_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` ADD CONSTRAINT \`FK_fe228a77fedbe9033278b705a18\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` ADD CONSTRAINT \`FK_ab153f36e61d7c0d0ccc945a0ea\` FOREIGN KEY (\`schoolId\`) REFERENCES \`school_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_3152c2efd3647b7aa68f0743690\` FOREIGN KEY (\`rankedAcademicId\`) REFERENCES \`ranked_academic_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_3a4584dd964dbef7194e4b3734c\` FOREIGN KEY (\`schoolId\`) REFERENCES \`school_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_52ab40f5accd7c3d6bc100389b7\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` ADD CONSTRAINT \`FK_7652c87043fce32940a34c20153\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` ADD CONSTRAINT \`FK_02fcbe5517ce42bbf470ab1d7ae\` FOREIGN KEY (\`certificateId\`) REFERENCES \`certificate_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` ADD CONSTRAINT \`FK_7ace3a698f0341fa84d6558e828\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` ADD CONSTRAINT \`FK_48c0503ac7bbf1d96d26fb9c356\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` ADD CONSTRAINT \`FK_c312553cc0e1a4328d69eb4d449\` FOREIGN KEY (\`certificateId\`) REFERENCES \`certificate_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` ADD CONSTRAINT \`FK_789640cfc0373a2d3442c1c5bbf\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` ADD CONSTRAINT \`FK_cbcff6bccb35fe0a22d56c88b5d\` FOREIGN KEY (\`certificateId\`) REFERENCES \`certificate_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` ADD CONSTRAINT \`FK_87a1829647c584d7ac7a0e70296\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` DROP FOREIGN KEY \`FK_87a1829647c584d7ac7a0e70296\``);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` DROP FOREIGN KEY \`FK_cbcff6bccb35fe0a22d56c88b5d\``);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` DROP FOREIGN KEY \`FK_789640cfc0373a2d3442c1c5bbf\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` DROP FOREIGN KEY \`FK_c312553cc0e1a4328d69eb4d449\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` DROP FOREIGN KEY \`FK_48c0503ac7bbf1d96d26fb9c356\``);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` DROP FOREIGN KEY \`FK_7ace3a698f0341fa84d6558e828\``);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` DROP FOREIGN KEY \`FK_02fcbe5517ce42bbf470ab1d7ae\``);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` DROP FOREIGN KEY \`FK_7652c87043fce32940a34c20153\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_52ab40f5accd7c3d6bc100389b7\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_3a4584dd964dbef7194e4b3734c\``);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` DROP FOREIGN KEY \`FK_3152c2efd3647b7aa68f0743690\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` DROP FOREIGN KEY \`FK_ab153f36e61d7c0d0ccc945a0ea\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` DROP FOREIGN KEY \`FK_fe228a77fedbe9033278b705a18\``);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` DROP FOREIGN KEY \`FK_1925ddf100616fa4d0b3e62574b\``);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` DROP FOREIGN KEY \`FK_1e728f6d21307865790753ee148\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_10b2a273ef381e46ae6fc67aa46\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_401509d24b0d71b01a0a0b98756\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` DROP FOREIGN KEY \`FK_24eca45ff584c922bdc0feef184\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` DROP FOREIGN KEY \`FK_8b9dfbac4c8959963a7c966d9b8\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` DROP FOREIGN KEY \`FK_7847c58187237b0e4b346cd49ef\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` DROP FOREIGN KEY \`FK_934c6ac69085740dd8f746d78e8\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_e79ee65cc62f38c795d889691d6\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_6b0550abd4604060249ef3aca5b\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_1b3900fd8753c2ca7f5daaf0afd\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` DROP FOREIGN KEY \`FK_5c10cf491690ed4d710718060b3\``);
        await queryRunner.query(`ALTER TABLE \`company_tag_entity\` DROP FOREIGN KEY \`FK_0abbd4350f976aabf730c5ba4c7\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_e23e7775e939d1ae14b4e7ee473\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_a30325f01e55247deb78498649a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_5e416a6fdc03f66de9b51d6e96a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_bbd7576066b053fc16f76617e00\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` DROP FOREIGN KEY \`FK_d0f523287bb6a13d53905962391\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` DROP FOREIGN KEY \`FK_5cb06862a9b92d9f8639209d162\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` DROP FOREIGN KEY \`FK_88e7580f6462c6b098083daeba1\``);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` DROP FOREIGN KEY \`FK_d2bc7c7b359750c32dfed9bdc76\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` DROP FOREIGN KEY \`FK_cee737ea7a02788a001cdd9ebab\``);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` DROP FOREIGN KEY \`FK_61b6e6c0ebe5a443ad738f394d5\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_8f6fff6b2239738702560ddb52b\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_4bb7b007ab6347dad742d533715\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_e7b0e7181fd855f9f1e812e592b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_1b8bcad73a6becddb565dc4efd7\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_0d66f3e9f22d5e62be548a6f02b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_165d4ff9dcabc15def46ffa8c20\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_9c391e2018f807b6843cdee35ca\``);
        await queryRunner.query(`ALTER TABLE \`address_entity\` DROP FOREIGN KEY \`FK_d96e5f9914d0f80c787b8da289b\``);
        await queryRunner.query(`DROP INDEX \`IDX_88a1485872bf594d91855aaf99\` ON \`user_certificate_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_137366505dda765a2502e46f2f\` ON \`user_tagged_certificate_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_17047910dd948275a7fbaec3ff\` ON \`cv_certificate_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_9aac5475ecef981ded65e4f795\` ON \`user_tagged_school_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_6b92f1f20f2469c59d3780fc06\` ON \`user_school_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_d569718f45522c277173602332\` ON \`user_skill_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_3f52e8df570dd7586c12a7dadd\` ON \`user_tagged_skill_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_8c99e8dfb3daee272748878669\` ON \`cv_work_experience_skill_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_fdb82033eaa6d2f4cf7a44bbd3\` ON \`user_tagged_company_tag_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_edea0cf6b6e524794e2324de90\` ON \`cv_work_experience_position_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_d8d247814af7dbb26a8ae81f54\` ON \`user_tagged_position_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8bac637b3db062b19fc103cf2\` ON \`user_position_entity\``);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_activities_entity\` ADD CONSTRAINT \`FK_87a1829647c584d7ac7a0e70296\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` CHANGE \`certificateId\` \`certificateId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_88a1485872bf594d91855aaf99\` ON \`user_certificate_entity\` (\`userId\`, \`certificateId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` ADD CONSTRAINT \`FK_cbcff6bccb35fe0a22d56c88b5d\` FOREIGN KEY (\`certificateId\`) REFERENCES \`certificate_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_certificate_entity\` ADD CONSTRAINT \`FK_789640cfc0373a2d3442c1c5bbf\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`certificate_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` CHANGE \`certificateId\` \`certificateId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_137366505dda765a2502e46f2f\` ON \`user_tagged_certificate_entity\` (\`userId\`, \`certificateId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` ADD CONSTRAINT \`FK_c312553cc0e1a4328d69eb4d449\` FOREIGN KEY (\`certificateId\`) REFERENCES \`certificate_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_certificate_entity\` ADD CONSTRAINT \`FK_48c0503ac7bbf1d96d26fb9c356\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` CHANGE \`certificateId\` \`certificateId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` CHANGE \`content\` \`content\` text NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_17047910dd948275a7fbaec3ff\` ON \`cv_certificate_entity\` (\`userId\`, \`certificateId\`)`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` ADD CONSTRAINT \`FK_7ace3a698f0341fa84d6558e828\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` ADD CONSTRAINT \`FK_02fcbe5517ce42bbf470ab1d7ae\` FOREIGN KEY (\`certificateId\`) REFERENCES \`certificate_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_honors_awards_entity\` ADD CONSTRAINT \`FK_7652c87043fce32940a34c20153\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`schoolId\` \`schoolId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`rankedAcademicId\` \`rankedAcademicId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` CHANGE \`content\` \`content\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_52ab40f5accd7c3d6bc100389b7\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_3a4584dd964dbef7194e4b3734c\` FOREIGN KEY (\`schoolId\`) REFERENCES \`school_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_education_entity\` ADD CONSTRAINT \`FK_3152c2efd3647b7aa68f0743690\` FOREIGN KEY (\`rankedAcademicId\`) REFERENCES \`ranked_academic_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`school_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` CHANGE \`schoolId\` \`schoolId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9aac5475ecef981ded65e4f795\` ON \`user_tagged_school_entity\` (\`schoolId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` ADD CONSTRAINT \`FK_ab153f36e61d7c0d0ccc945a0ea\` FOREIGN KEY (\`schoolId\`) REFERENCES \`school_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_school_entity\` ADD CONSTRAINT \`FK_fe228a77fedbe9033278b705a18\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` CHANGE \`schoolId\` \`schoolId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_6b92f1f20f2469c59d3780fc06\` ON \`user_school_entity\` (\`schoolId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` ADD CONSTRAINT \`FK_1925ddf100616fa4d0b3e62574b\` FOREIGN KEY (\`schoolId\`) REFERENCES \`school_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_school_entity\` ADD CONSTRAINT \`FK_1e728f6d21307865790753ee148\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ranked_academic_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d569718f45522c277173602332\` ON \`user_skill_entity\` (\`skillId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_10b2a273ef381e46ae6fc67aa46\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_401509d24b0d71b01a0a0b98756\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_3f52e8df570dd7586c12a7dadd\` ON \`user_tagged_skill_entity\` (\`skillId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` ADD CONSTRAINT \`FK_24eca45ff584c922bdc0feef184\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_skill_entity\` ADD CONSTRAINT \`FK_8b9dfbac4c8959963a7c966d9b8\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` CHANGE \`cvWorkExperienceId\` \`cvWorkExperienceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_8c99e8dfb3daee272748878669\` ON \`cv_work_experience_skill_entity\` (\`cvWorkExperienceId\`, \`skillId\`)`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` ADD CONSTRAINT \`FK_7847c58187237b0e4b346cd49ef\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_skill_entity\` ADD CONSTRAINT \`FK_934c6ac69085740dd8f746d78e8\` FOREIGN KEY (\`cvWorkExperienceId\`) REFERENCES \`cv_work_experience_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`workFromId\` \`workFromId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`jobLevelId\` \`jobLevelId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`companyTagId\` \`companyTagId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`content\` \`content\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` CHANGE \`endDate\` \`endDate\` datetime NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_e79ee65cc62f38c795d889691d6\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_6b0550abd4604060249ef3aca5b\` FOREIGN KEY (\`workFromId\`) REFERENCES \`work_from_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_1b3900fd8753c2ca7f5daaf0afd\` FOREIGN KEY (\`jobLevelId\`) REFERENCES \`job_level_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_entity\` ADD CONSTRAINT \`FK_5c10cf491690ed4d710718060b3\` FOREIGN KEY (\`companyTagId\`) REFERENCES \`company_tag_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_tag_entity\` CHANGE \`companyInfoId\` \`companyInfoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_tag_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_tag_entity\` ADD CONSTRAINT \`FK_0abbd4350f976aabf730c5ba4c7\` FOREIGN KEY (\`companyInfoId\`) REFERENCES \`company_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_e23e7775e939d1ae14b4e7ee473\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_a30325f01e55247deb78498649a\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_5e416a6fdc03f66de9b51d6e96a\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_bbd7576066b053fc16f76617e00\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` CHANGE \`companyTagId\` \`companyTagId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_fdb82033eaa6d2f4cf7a44bbd3\` ON \`user_tagged_company_tag_entity\` (\`companyTagId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` ADD CONSTRAINT \`FK_d0f523287bb6a13d53905962391\` FOREIGN KEY (\`companyTagId\`) REFERENCES \`company_tag_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_company_tag_entity\` ADD CONSTRAINT \`FK_5cb06862a9b92d9f8639209d162\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` CHANGE \`cvWorkExperienceId\` \`cvWorkExperienceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_edea0cf6b6e524794e2324de90\` ON \`cv_work_experience_position_entity\` (\`cvWorkExperienceId\`, \`positionId\`)`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` ADD CONSTRAINT \`FK_88e7580f6462c6b098083daeba1\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_work_experience_position_entity\` ADD CONSTRAINT \`FK_d2bc7c7b359750c32dfed9bdc76\` FOREIGN KEY (\`cvWorkExperienceId\`) REFERENCES \`cv_work_experience_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_d8d247814af7dbb26a8ae81f54\` ON \`user_tagged_position_entity\` (\`positionId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` ADD CONSTRAINT \`FK_cee737ea7a02788a001cdd9ebab\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_tagged_position_entity\` ADD CONSTRAINT \`FK_61b6e6c0ebe5a443ad738f394d5\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_c8bac637b3db062b19fc103cf2\` ON \`user_position_entity\` (\`positionId\`, \`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_8f6fff6b2239738702560ddb52b\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_4bb7b007ab6347dad742d533715\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`work_from_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`job_level_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`jobLevelId\` \`jobLevelId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`objective\` \`objective\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`interest\` \`interest\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_e7b0e7181fd855f9f1e812e592b\` FOREIGN KEY (\`jobLevelId\`) REFERENCES \`job_level_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_1b8bcad73a6becddb565dc4efd7\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_0d66f3e9f22d5e62be548a6f02b\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_165d4ff9dcabc15def46ffa8c20\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_9c391e2018f807b6843cdee35ca\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`parentId\` \`parentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` ADD CONSTRAINT \`FK_d96e5f9914d0f80c787b8da289b\` FOREIGN KEY (\`parentId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` DROP COLUMN \`year\``);
        await queryRunner.query(`ALTER TABLE \`cv_certificate_entity\` ADD \`date\` datetime NOT NULL`);
    }

}
