import { MigrationInterface, QueryRunner } from "typeorm";

export class mg1655666295984 implements MigrationInterface {
    name = 'mg1655666295984'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`cv_section_control_type_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`tag\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, UNIQUE INDEX \`tag_unique\` (\`tag\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_sec_builder_section_control_type_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` int NOT NULL, \`isGlobal\` tinyint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`cvSecBuilderId\` int NULL, \`cvSectionControlTypeId\` int NULL, INDEX \`IDX_f7b90d6688c15e1eaea696aa87\` (\`isGlobal\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`cv_sec_builder_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` int NOT NULL, \`isGlobal\` tinyint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, INDEX \`IDX_4dac628711a8f32e51734e9a36\` (\`isGlobal\`), UNIQUE INDEX \`userId_name_unique\` (\`name\`, \`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`job_level_entity\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, INDEX \`IDX_bd3ae16a1281da016b39e86fef\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` DROP FOREIGN KEY \`FK_d96e5f9914d0f80c787b8da289b\``);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`parentId\` \`parentId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` DROP FOREIGN KEY \`FK_0dec14fd40d546fdb101fb8408b\``);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` CHANGE \`userSkillsId\` \`userSkillsId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_401509d24b0d71b01a0a0b98756\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_10b2a273ef381e46ae6fc67aa46\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_165d4ff9dcabc15def46ffa8c20\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_0d66f3e9f22d5e62be548a6f02b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_1b8bcad73a6becddb565dc4efd7\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` DROP FOREIGN KEY \`FK_0934e734a3f97d37788198f296c\``);
        await queryRunner.query(`ALTER TABLE \`user_entity\` DROP FOREIGN KEY \`FK_5e96f265469267c6c27191b6877\``);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`userInfoId\` \`userInfoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`companyInfoId\` \`companyInfoId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_5e416a6fdc03f66de9b51d6e96a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_a30325f01e55247deb78498649a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_e23e7775e939d1ae14b4e7ee473\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_4bb7b007ab6347dad742d533715\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_8f6fff6b2239738702560ddb52b\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`userId\` \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` DROP FOREIGN KEY \`FK_f6235c0a767743f986d9cdffe3b\``);
        await queryRunner.query(`ALTER TABLE \`position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` CHANGE \`userPositionsId\` \`userPositionsId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`work_from_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` ADD CONSTRAINT \`FK_d96e5f9914d0f80c787b8da289b\` FOREIGN KEY (\`parentId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` ADD CONSTRAINT \`FK_0dec14fd40d546fdb101fb8408b\` FOREIGN KEY (\`userSkillsId\`) REFERENCES \`user_skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_401509d24b0d71b01a0a0b98756\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_10b2a273ef381e46ae6fc67aa46\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_165d4ff9dcabc15def46ffa8c20\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_0d66f3e9f22d5e62be548a6f02b\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_1b8bcad73a6becddb565dc4efd7\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` ADD CONSTRAINT \`FK_29b90730a1a208c7b54a1eee9b0\` FOREIGN KEY (\`cvSecBuilderId\`) REFERENCES \`cv_sec_builder_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` ADD CONSTRAINT \`FK_4317c257e253e4012b8cdda3e47\` FOREIGN KEY (\`cvSectionControlTypeId\`) REFERENCES \`cv_section_control_type_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` ADD CONSTRAINT \`FK_7c99c304cf66aeed6e382e352cc\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` ADD CONSTRAINT \`FK_0934e734a3f97d37788198f296c\` FOREIGN KEY (\`userInfoId\`) REFERENCES \`user_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` ADD CONSTRAINT \`FK_5e96f265469267c6c27191b6877\` FOREIGN KEY (\`companyInfoId\`) REFERENCES \`company_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_5e416a6fdc03f66de9b51d6e96a\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_a30325f01e55247deb78498649a\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_e23e7775e939d1ae14b4e7ee473\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_4bb7b007ab6347dad742d533715\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_8f6fff6b2239738702560ddb52b\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` ADD CONSTRAINT \`FK_f6235c0a767743f986d9cdffe3b\` FOREIGN KEY (\`userPositionsId\`) REFERENCES \`user_position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`position_entity\` DROP FOREIGN KEY \`FK_f6235c0a767743f986d9cdffe3b\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_8f6fff6b2239738702560ddb52b\``);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` DROP FOREIGN KEY \`FK_4bb7b007ab6347dad742d533715\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_e23e7775e939d1ae14b4e7ee473\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_a30325f01e55247deb78498649a\``);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` DROP FOREIGN KEY \`FK_5e416a6fdc03f66de9b51d6e96a\``);
        await queryRunner.query(`ALTER TABLE \`user_entity\` DROP FOREIGN KEY \`FK_5e96f265469267c6c27191b6877\``);
        await queryRunner.query(`ALTER TABLE \`user_entity\` DROP FOREIGN KEY \`FK_0934e734a3f97d37788198f296c\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_entity\` DROP FOREIGN KEY \`FK_7c99c304cf66aeed6e382e352cc\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` DROP FOREIGN KEY \`FK_4317c257e253e4012b8cdda3e47\``);
        await queryRunner.query(`ALTER TABLE \`cv_sec_builder_section_control_type_entity\` DROP FOREIGN KEY \`FK_29b90730a1a208c7b54a1eee9b0\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_1b8bcad73a6becddb565dc4efd7\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_0d66f3e9f22d5e62be548a6f02b\``);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` DROP FOREIGN KEY \`FK_165d4ff9dcabc15def46ffa8c20\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_10b2a273ef381e46ae6fc67aa46\``);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` DROP FOREIGN KEY \`FK_401509d24b0d71b01a0a0b98756\``);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` DROP FOREIGN KEY \`FK_0dec14fd40d546fdb101fb8408b\``);
        await queryRunner.query(`ALTER TABLE \`address_entity\` DROP FOREIGN KEY \`FK_d96e5f9914d0f80c787b8da289b\``);
        await queryRunner.query(`ALTER TABLE \`work_from_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` CHANGE \`userPositionsId\` \`userPositionsId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`position_entity\` ADD CONSTRAINT \`FK_f6235c0a767743f986d9cdffe3b\` FOREIGN KEY (\`userPositionsId\`) REFERENCES \`user_position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`positionId\` \`positionId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_8f6fff6b2239738702560ddb52b\` FOREIGN KEY (\`positionId\`) REFERENCES \`position_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_position_entity\` ADD CONSTRAINT \`FK_4bb7b007ab6347dad742d533715\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_e23e7775e939d1ae14b4e7ee473\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_a30325f01e55247deb78498649a\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`company_info_entity\` ADD CONSTRAINT \`FK_5e416a6fdc03f66de9b51d6e96a\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`companyInfoId\` \`companyInfoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`userInfoId\` \`userInfoId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` ADD CONSTRAINT \`FK_5e96f265469267c6c27191b6877\` FOREIGN KEY (\`companyInfoId\`) REFERENCES \`company_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_entity\` ADD CONSTRAINT \`FK_0934e734a3f97d37788198f296c\` FOREIGN KEY (\`userInfoId\`) REFERENCES \`user_info_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressVillageId\` \`addressVillageId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressDistrictId\` \`addressDistrictId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`addressProvinceId\` \`addressProvinceId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_1b8bcad73a6becddb565dc4efd7\` FOREIGN KEY (\`addressVillageId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_0d66f3e9f22d5e62be548a6f02b\` FOREIGN KEY (\`addressDistrictId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_info_entity\` ADD CONSTRAINT \`FK_165d4ff9dcabc15def46ffa8c20\` FOREIGN KEY (\`addressProvinceId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`skillId\` \`skillId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`userId\` \`userId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_10b2a273ef381e46ae6fc67aa46\` FOREIGN KEY (\`skillId\`) REFERENCES \`skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_skill_entity\` ADD CONSTRAINT \`FK_401509d24b0d71b01a0a0b98756\` FOREIGN KEY (\`userId\`) REFERENCES \`user_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` CHANGE \`userSkillsId\` \`userSkillsId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`skill_entity\` ADD CONSTRAINT \`FK_0dec14fd40d546fdb101fb8408b\` FOREIGN KEY (\`userSkillsId\`) REFERENCES \`user_skill_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`parentId\` \`parentId\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` CHANGE \`deletedAt\` \`deletedAt\` datetime(6) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`address_entity\` ADD CONSTRAINT \`FK_d96e5f9914d0f80c787b8da289b\` FOREIGN KEY (\`parentId\`) REFERENCES \`address_entity\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`DROP INDEX \`IDX_bd3ae16a1281da016b39e86fef\` ON \`job_level_entity\``);
        await queryRunner.query(`DROP TABLE \`job_level_entity\``);
        await queryRunner.query(`DROP INDEX \`userId_name_unique\` ON \`cv_sec_builder_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_4dac628711a8f32e51734e9a36\` ON \`cv_sec_builder_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_sec_builder_entity\``);
        await queryRunner.query(`DROP INDEX \`IDX_f7b90d6688c15e1eaea696aa87\` ON \`cv_sec_builder_section_control_type_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_sec_builder_section_control_type_entity\``);
        await queryRunner.query(`DROP INDEX \`tag_unique\` ON \`cv_section_control_type_entity\``);
        await queryRunner.query(`DROP TABLE \`cv_section_control_type_entity\``);
    }

}
