version: "3.7"
services:
  itconnect_mail:
    image: itconnect/mail
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
    restart: always
    build: .
    volumes:
      - "itconnect_ssl:/etc/letsencrypt"

networks:
  default:
    external:
      name: 'itconnect_nginx'

volumes:
  itconnect_ssl:
    external: true
