version: "3.7"
services:
  itconnect_db_mysql_local:
    image: mysql:8.0.29
    ports:
      - "10.8.0.1:3305:3306"
    expose:
      - "3306"
    restart: always
    volumes:
      - "itconnect_mysql_data_local:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/my.cnf"
    environment:
      - MYSQL_DATABASE=itconnect
      - MYSQL_ROOT_PASSWORD=toor
      - TZ=Asia/Ho_Chi_Minh

networks:
  default:
    external:
      name: 'itconnect_nginx'

volumes:
  itconnect_mysql_data_local:
    external: true