name: itconnect_frontend
on:
  push:
    branches:
      - main
    # paths:
      # - 'frontend/**'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

  