name: itconnect_frontend
on:
  push:
    branches:
      - main
    # paths:
      # - 'frontend/**'

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN  }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: ./frontend
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets. DOCKERHUB_USERNAME }}/itconnect_frontend

      - name: Verify
          run: echo ${{ steps.docker_build.outputs.digest }}