version: "3.7"
services:
  itconnect_frontend:
    image: wawahuy/itconnect_frontend:latest
    volumes:
      - "itconnect_fe_built:/var/frontend"

networks:
  default:
    external:
      name: 'itconnect_nginx'

volumes:
  itconnect_fe_built:
    external: true
